##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.8"

# OS detection
module OS
  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end
end

require "yaml"

Vagrant.configure("2") do |config|

    # Box setup
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box"

    # Get box settings
    box = YAML.load_file(File.dirname(__FILE__) + "/config/box_setting.yml")

    config.vm.provider :virtualbox do |v|
        v.name = box["name"]
        v.customize [
            "modifyvm", :id,
            "--name", box["name"],
            "--memory", box["memory"],
            "--natdnshostresolver1", "on",
            "--cpus", box["cpus"]
        ]
    end

    # Networking
    config.vm.hostname = box["name"]
    config.vm.network :private_network, ip: box["ip"] # Base box

    # Use host ssh
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 22, host: 1200, id: "ssh", auto_correct: true

    # OSX and Linux shares
    # Sync code folder
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    # Get ansible vars
    ansible_vars = YAML.load_file(File.dirname(__FILE__) + "/config/ansible_vars.yml")

    # Host setup

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.aliases = ansible_vars["servername"]

    config.vm.provision "shell" do |s|
        s.inline = "sudo rm -rf $1 && sudo mkdir -p $1 && sudo chown -R vagrant:vagrant $1"
        s.args =  [ansible_vars["docroot"]]
    end

    config.vm.provision "shell" do |s|
        s.inline = "cd $1 && ln -s /vagrant/src/$2 $2"
        s.args =  [ansible_vars["docroot"], ansible_vars["app_name"]]
    end

    # Adding the ssh key into the VM
    config.vm.provision "shell" do |s|
        s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo $1 | tee -a /home/vagrant/.ssh/authorized_keys"
        s.args = [File.read(File.expand_path("~/.ssh/id_rsa.pub"))]
    end

    # Git config file
    config.vm.provision "file", source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"

    # Provision
    # Get ansible play settings
    ansible_play_settings = YAML.load_file(File.dirname(__FILE__) + "/config/ansible_settings.yml")

    config.vm.provision :ansible do |ansible|
        ansible.limit = ansible_play_settings["limit"]
        ansible.playbook = ansible_play_settings["playbook"]
        ansible.tags = ansible_play_settings["tags"]
        ansible.extra_vars = "config/ansible_vars.yml"
    end

end