##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.8"

# OS detection
module OS
  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end
end

require "yaml"

Vagrant.configure("2") do |config|

    # Box setup
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box"

    # Get box settings
    box = YAML.load_file(File.dirname(__FILE__) + "/config/box_setting.yml")

    config.vm.provider :virtualbox do |v|
        v.name = box["name"]
        v.customize [
            "modifyvm", :id,
            "--name", box["name"],
            "--memory", box["memory"],
            "--natdnshostresolver1", "on",
            "--cpus", box["cpus"]
        ]
    end

    # Host setup
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.aliases = box["alias"].join(" ")


    # Networking
    config.vm.hostname = box["name"]
    config.vm.network :private_network, ip: box["ip"] # Base box

    # Use host ssh
    config.ssh.forward_agent = true
    config.vm.network "forwarded_port", guest: 22, host: 1200, id: "ssh", auto_correct: true

    # OSX and Linux shares
    # Sync code folder
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    root_dir = box["docroot"].slice(0..(box["docroot"].index("/", 1)))

    base_dir = root_dir

    position = box["docroot"].rindex("/")
    if position.nil?
        base_dir = box["docroot"].slice(0..position)
    end

    config.vm.provision "shell" do |s|
        s.inline = "sudo rm -rf $1 && sudo mkdir -p $2 && sudo chown -R vagrant:vagrant $2"
        s.args =  [root_dir, base_dir]
    end

    config.vm.provision "shell" do |s|
        s.inline = "cd $1 && ln -s /vagrant/src src"
        s.args =  base_dir
    end

    # Adding the ssh key into the VM
    config.vm.provision "shell" do |s|
        s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo $1 | tee -a /home/vagrant/.ssh/authorized_keys"
        s.args = [File.read(File.expand_path("~/.ssh/id_rsa.pub"))]
    end

    # Git config file
    config.vm.provision "file", source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"

    # Manually install ansible 1.9.4 because 2.0 is incompatibile
    # @see https://github.com/geerlingguy/drupal-vm/issues/372
    #config.vm.provision "shell", inline: "sudo apt-get update"
    #config.vm.provision "shell", inline: "sudo apt-get install -y python-pip python-dev"
    #config.vm.provision "shell", inline: "sudo pip install ansible==1.9.4"
    #config.vm.provision "shell", inline: "sudo cp /usr/local/bin/ansible /usr/bin/ansible"

    # Provision
    # Get ansible settings
    settings = YAML.load_file(File.dirname(__FILE__) + "/config/ansible_settings.yml")

    #config.vm.provision "ansible_local" do |ansible|
#        ansible.install = false # we already installed it earlier
 #       ansible.limit = settings["limit"]
  #      ansible.playbook = settings["playbook"]
   #     ansible.tags= settings["tags"]
    #end

end