---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, npm]
    timezone: UTC
    locale: pt_BR.UTF-8
nginx:
    install: '1'
    docroot: /dohernandez/dev/public
    servername: dev.dohernandez.io
mysql:
    install: '1'
    root_password: dohernandez
    database: dohernandez
    user: dohernandez
    password: dohernandez
    dump: ''
mongodb:
    install: '1'
redis:
    install: '1'
    port: '6379'
php5x:
    install: '0'
    ppa: php5-5.6
    packages:
      - php5-cli
      - php5-intl
      - php5-mcrypt
      - php5-curl
      - php5-mysql
      - php5-mongo
php7x:
    install: '1'
    ppa: php
    packages:
      - libapache2-mod-php7.0
      - php7.0-cli
      - php7.0-common
      - php7.0-curl
      - php7.0-intl
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-dev
      - php7.0-gd
      - php7.0-mbstring
      - php7.0-json
      - php7.0-opcache
      - php7.0-xml
      - libpcre3-dev
      - php7.0-odbc
      - php7.0-pgsql
      - php7.0-bz2
xdebug:
    install: '1'
composer:
    install: '1'
