---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, npm, nmap]
    timezone: UTC
    locale: de_DE.UTF-8
nginx:
    install: '1'
    vhost:
      dohernandez:
        docroot: /vagrant/src/public
        servername: dev.dohernandez.io
      eventsourcing:
        docroot: /vagrant/src/eventsourcing/public
        servername: dev.eventsourcing.io
mysql:
    install: '1'
    root_password: dohernandez
    databases:
      dohernandez:
        user: dohernandez
        password: dohernandez
        dump: ''
mongodb:
    install: '1'
redis:
    install: '1'
    port: '6379'
php5x:
    install: '0'
    ppa: php5-5.6
    packages:
      - php5-cli
      - php5-intl
      - php5-mcrypt
      - php5-curl
      - php5-mysql
      - php5-mongo
      - php5-dev
php7x:
    install: '1'
    ppa: php
    packages:
      - libapache2-mod-php7.0
      - php7.0-cli
      - php7.0-common
      - php7.0-curl
      - php7.0-intl
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-dev
      - php7.0-gd
      - php7.0-mbstring
      - php7.0-json
      - php7.0-opcache
      - php7.0-xml
      - libpcre3-dev
      - php7.0-odbc
      - php7.0-pgsql
      - php7.0-bz2
      - php7.0-zip
      - php7.0-bcmath
xdebug:
    install: '1'
composer:
    install: '1'
