# aliases to provide for your /etc/hosts.
servername: dev.lawton.io
# Where to mount the /vagrant into the machine
docroot: "/dohernandez"
# App name
app_name: lawton

# nginx asible variables. Overwrite the nginx variables defined in the file var/all.yml
nginx:
    docroot: "{{docroot}}/{{app_name}}/public"
    servername: "{{servername}}"

# mysql asible variables. Overwrite the mysql variables defined in the file var/all.yml
mysql:
    root_password: dohernandez
    database: dohernandez
    user: dohernandez
    password: dohernandez
    dump: ''