---
- name: Setup the development VM
  hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  # Run before roles
  pre_tasks:
    - apt: update_cache=yes
      become: yes
  roles:
   - { role: server,        tags: ["server", "nginx", "mysql", "mongodb", "redis", "php", "xdebug", "composer", "app", "dev-app"] }
   - { role: nginx,         tags: ["nginx", "app", "dev-app"] }
   - { role: mysql,         tags: ["mysql", "app", "dev-app"] }
   - { role: mongodb,       tags: ["mongodb"] }
   - { role: redis,         tags: ["redis"] }
   - { role: php-5.x,       tags: ["php", "app", "dev-app"], when: php5x.install == "1" }
   - { role: php-7.x,       tags: ["php", "app", "dev-app"], when: php7x.install == "1" }
   - { role: xdebug,        tags: ["xdebug", "dev-app"] }
   - { role: composer,      tags: ["composer", "app", "dev-app"] }
   - { role: phpunit,   tags: ["phpunit", "dev-app"] }
   - { role: app,           tags: ["app", "dev-app"] }